apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-server
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-server
  template:
    metadata:
      labels:
        app: app1-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
        - name: dockerhub-secret
      containers:
        - name: app1-server
          image: ghcr.io/yogeshhome/app1-server:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://root:Kskarthik21@app1-mongo:27017/mydb?authSource=admin"
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: app1-server
  namespace: production
spec:
  selector:
    app: app1-server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: ClusterIP

