apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yogeshhome/my-hosting-server.git
    targetRevision: main
    path: k3s/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  # Namespace drift
  - group: ""
    kind: Namespace
    name: app1
    jsonPointers:
    - /metadata
  # Service drift (clusterIP, etc.)
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP
    - /spec/clusterIPs
    - /spec/healthCheckNodePort
    - /spec/sessionAffinity
  # Deployment drift (status fields)
  - group: apps
    kind: Deployment
    jsonPointers:
    - /status

