name: CI Pipeline

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client image
        run: |
          docker buildx build \
            -f apps/app1/Dockerfile.client \
            -t ${{ secrets.DOCKER_USERNAME }}/my-hosting-sever:client-${{ github.sha }} \
            -t ${{ secrets.DOCKER_USERNAME }}/my-hosting-sever:client-latest \
            ./apps/app1 --push

      - name: Build and push server image
        run: |
          docker buildx build \
            -f apps/app1/Dockerfile.server \
            -t ${{ secrets.DOCKER_USERNAME }}/my-hosting-sever:server-${{ github.sha }} \
            -t ${{ secrets.DOCKER_USERNAME }}/my-hosting-sever:server-latest \
            ./apps/app1 --push
