name: CI Pipeline

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set in repo secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set in repo secrets

      # Step 3: Build and push client image
      - name: Build and push client image
        run: |
          CLIENT_IMAGE=${{ secrets.DOCKER_USERNAME }}/my-hosting-sever:client-${GITHUB_SHA}
          CLIENT_LATEST=${{ secrets.DOCKER_USERNAME }}/my-hosting-sever:client-latest

          docker build -f apps/app1/Dockerfile.client -t "$CLIENT_IMAGE" ./apps/app1
          docker tag "$CLIENT_IMAGE" "$CLIENT_LATEST"
          docker push "$CLIENT_IMAGE"
          docker push "$CLIENT_LATEST"

      # Step 4: Build and push server image
      - name: Build and push server image
        run: |
          SERVER_IMAGE=${{ secrets.DOCKER_USERNAME }}/my-hosting-sever:server-${GITHUB_SHA}
          SERVER_LATEST=${{ secrets.DOCKER_USERNAME }}/my-hosting-sever:server-latest

          docker build -f apps/app1/Dockerfile.server -t "$SERVER_IMAGE" ./apps/app1
          docker tag "$SERVER_IMAGE" "$SERVER_LATEST"
          docker push "$SERVER_IMAGE"
          docker push "$SERVER_LATEST"
